export const TEST_SECTIONS = [
  {
    id: "reading",
    title: "Reading",
    description: "Academic passages with True/False, headings, multiple choice and short-answer questions.",
    href: "/reading",
    testsAvailable: 12,
    durationMinutes: 60,
    questionCount: 40,
    difficulty: "medium",
    color: "bg-indigo-50 text-accent",
    icon: "book",
  },
  {
    id: "listening",
    title: "Listening",
    description: "Four-part audio test with form completion, MCQ and map labelling questions.",
    href: "/listening",
    testsAvailable: 10,
    durationMinutes: 30,
    questionCount: 40,
    difficulty: "medium",
    color: "bg-emerald-50 text-success",
    icon: "headphones",
  },
  {
    id: "writing",
    title: "Writing",
    description: "Task 1 chart description and Task 2 essay, with instant AI-powered band feedback.",
    href: "/writing",
    testsAvailable: 8,
    durationMinutes: 60,
    questionCount: 2,
    difficulty: "hard",
    color: "bg-violet-50 text-violet-600",
    icon: "pencil",
  },
  {
    id: "speaking",
    title: "Speaking",
    description: "Three-part interview simulation with cue cards and follow-up discussion questions.",
    href: "/speaking",
    testsAvailable: 9,
    durationMinutes: 15,
    questionCount: 3,
    difficulty: "easy",
    color: "bg-amber-50 text-amber-600",
    icon: "mic",
  },
];
